### ISSUE TITLE
Question actually....

### ISSUE THREAD

**Issue by robstoddard** [andmcgregor/cefgui#1]
I am having issues with the current build of CEF integrated with this, and since there's no libcef.so file included in this git, I have no baseline.

So I'm wondering, what version of CEF is this based on?

I'm currently operating under the assumption that it's branch 1750 since the commit where CEF was copied in (156790999cfb1f6e8aea3b03a37a5ef7c7f2a271) is dated Sun Nov 16 2014.  As such, I'm going to build and see if I can work with this version of CEF.  Whether it works or not will be posted as a follow-up comment to this issue.

Thank you

Rob

**Comment by andmcgregor** [comment]
Hi, I believe the libcef.co file was from the 1738 revision based on the version file here: https://github.com/andmcgregor/cefgui/blob/master/cef/linux/include/cef_version.h

**Comment by robstoddard** [comment]
I solved the issue.   I had a problem with that cef version as my system has a newer libgcrypt.   The CEF resource files lacked the resources that the latest CEF version requires.  Once I removed the resources that were put into the bin directory, removed the copy-in of the included-in-this-project resources and copied the resources from the latest CEF, the project worked beautifully.
